"""Generate a paper kit's ``paper.bib`` as the CITED SUBSET of the shared corpus.

The one-master rule (``paper/literature/README.md``): the shared bib lives in the
science organ, one master per DIRECTION, and a paper repo's own bib is a subset
copied out of it with **keys unchanged**. A second hand-written bib is the
dual-truth failure with citation keys -- a key that drifts between two bibs
produces a wrong citation that compiles cleanly. So this file exists to make the
venue bib build output rather than a source of truth.

Two properties are deliberate:

* **It fails loudly on an unresolved key.** A cited key with no entry renders as
  a bare ``?`` in the PDF, which is the failure mode a silent generator would
  ship. Missing keys are an error, never a warning.
* **It strips corpus-curation fields.** The masters are a CURATION record and
  their ``note`` fields say things like ``CANDIDATE -- verify+download`` or
  ``was ABSENT from this bib until 2026-08-07``. natbib's styles RENDER
  ``note``, so those sentences were typeset into the bibliography of a built
  PDF, where an automated desk check found them before we did. A venue bib is a
  citation artifact and carries no curation metadata: the master keeps the note,
  the generated subset never does.
* **It reads EVERY direction bib, not one.** The corpus has one master per
  direction and a paper cites across them; measuring a key's absence against a
  single index and reporting it as absence in general is a recorded defect in
  this repo (``CLAUDE.md``, and ``as6/evidence_and_story.md`` §5.2 where it
  nearly duplicated four entries).

The corpus location is NOT hard-coded: this repo is public, so an absolute path
would commit the owner's directory layout. It resolves from
``$SCIENCE_LITERATURE_DIR`` if set, else from a path relative to this checkout.

Keyless, no network, no model. Run it, then rebuild the kit::

    uv run python scripts/build_venue_bib.py as-6
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PAPER_ROOT = REPO_ROOT / "paper"

#: Where the shared corpus sits relative to this checkout, when the env var is
#: unset. Deliberately relative -- see the module docstring.
DEFAULT_CORPUS_RELATIVE = Path("..") / ".." / "personal" / "science" / "literature"

#: Every ``\cite``-family command natbib gives us. The trailing ``\*?`` catches
#: the starred forms, and the optional-argument groups catch ``\citep[see][]{k}``.
CITE_PATTERN = re.compile(
    r"\\(?:no)?cite[a-zA-Z]*\*?\s*(?:\[[^\]]*\]\s*){0,2}\{([^}]*)\}"
)

#: A LaTeX comment: an UNESCAPED ``%`` through end of line. Two properties are
#: load-bearing. It must not eat ``\%`` (a literal percent sign in prose), and
#: it must leave the newline in place, so a ``\citep{a,b%<newline>c}`` line
#: continuation still closes its brace group. A whole-line-only pattern was the
#: first version and it leaked: ``\citep{a} % cf. \citep{b}`` cited ``b``.
COMMENT_PATTERN = re.compile(r"(?m)(?<!\\)((?:\\\\)*)%.*$")

#: The start of a BibTeX entry, capturing its key.
ENTRY_PATTERN = re.compile(r"(?m)^@(\w+)\s*\{\s*([^,\s]+)\s*,")

#: First line of a generated bib. It is the marker that says "this kit is on the
#: one-master rule", and tests scope themselves to kits carrying it -- so a kit
#: still on a hand-written bib is visibly OUT of coverage rather than silently
#: passing, and joins coverage the moment it is migrated.
GENERATED_MARKER = "% GENERATED by scripts/build_venue_bib.py"


def corpus_dir() -> Path:
    """Resolve the shared-corpus directory, env var winning over the default."""
    override = os.environ.get("SCIENCE_LITERATURE_DIR")
    if override:
        return Path(override).expanduser().resolve()
    return (REPO_ROOT / DEFAULT_CORPUS_RELATIVE).resolve()


def master_bibs(corpus: Path) -> list[Path]:
    """Every direction's ``references.bib``, sorted for a deterministic output."""
    return sorted(corpus.glob("*/references.bib"))


def cited_keys(tex: str) -> set[str]:
    """Extract every key cited by *tex*, ignoring LaTeX comments."""
    body = COMMENT_PATTERN.sub(r"\1", tex)
    keys: set[str] = set()
    for group in CITE_PATTERN.findall(body):
        for key in group.split(","):
            key = key.strip()
            if key:
                keys.add(key)
    return keys


def parse_entries(bib: str) -> dict[str, str]:
    """Split a bib file into ``{key: entry text}`` by brace matching.

    Brace matching rather than a regex on ``\n}``: entries here carry ``note``
    fields with braces inside them, and a line-anchored terminator truncates
    those silently.
    """
    entries: dict[str, str] = {}
    for match in ENTRY_PATTERN.finditer(bib):
        start = match.start()
        depth = 0
        index = bib.index("{", start)
        for position in range(index, len(bib)):
            character = bib[position]
            if character == "{":
                depth += 1
            elif character == "}":
                depth -= 1
                if depth == 0:
                    entries[match.group(2)] = bib[start : position + 1]
                    break
    return entries


def entry_keys(bib: str) -> list[str]:
    """Every entry key in *bib*, in order and WITH REPEATS.

    ``parse_entries`` returns a dict, so a key defined twice inside one file
    collapses there with the last copy silently winning. That is the same
    one-master violation the cross-direction check exists to catch, one scope
    down, and this corpus has had exactly it -- a ``zou2024circuitbreakers``
    present twice and disagreeing with itself about a venue. So the repeats are
    kept here and counted by ``resolve_corpus``.
    """
    return [match.group(2) for match in ENTRY_PATTERN.finditer(bib)]


#: Fields that belong to the CURATION corpus and never to a venue bib. ``note``
#: is rendered by natbib's styles; ``abstract`` is dead weight that some styles
#: also emit. Both are properties of how WE track a reference, not of the
#: reference.
CURATION_FIELDS = ("note", "abstract")


def _depth_at(entry: str, index: int) -> int:
    """Brace depth just before *index*, counted from the start of *entry*."""
    return entry.count("{", 0, index) - entry.count("}", 0, index)


def strip_curation_fields(entry: str, fields: tuple[str, ...] = CURATION_FIELDS) -> str:
    """Remove each of *fields* from ONE bib entry, value and trailing comma.

    Three properties are load-bearing.

    * **Only at top level.** A field is stripped only when it sits directly
      inside the entry's own brace group (depth 1), so a ``title`` whose text
      happens to contain ``, note = ...`` is untouched.
    * **Brace-aware and quote-aware.** Values appear as ``{...}`` with nested
      braces and as ``"..."``; a line-anchored regex truncates the first kind
      silently, which is the same failure ``parse_entries`` documents.
    * **It does not reflow anything else.** Only the matched span leaves; the
      surrounding whitespace and field order are the master's.
    """
    for name in fields:
        pattern = re.compile(r"([{,])\s*" + re.escape(name) + r"\s*=\s*", re.IGNORECASE)
        position = 0
        while True:
            match = pattern.search(entry, position)
            if match is None:
                break
            if _depth_at(entry, match.start()) != 1:
                position = match.end()
                continue
            start = match.end()
            character = entry[start]
            if character == "{":
                depth = 0
                end = -1
                for index in range(start, len(entry)):
                    if entry[index] == "{":
                        depth += 1
                    elif entry[index] == "}":
                        depth -= 1
                        if depth == 0:
                            end = index + 1
                            break
                if end < 0:
                    raise SystemExit(f"unterminated {name} field in entry:\n{entry[:80]}")
            elif character == '"':
                end = entry.index('"', start + 1) + 1
            else:
                end = start
                while end < len(entry) and entry[end] not in ",}":
                    end += 1
            tail = entry[end:]
            without_space = tail.lstrip()
            if without_space.startswith(","):
                end += len(tail) - len(without_space) + 1
            entry = entry[: match.start()] + match.group(1) + entry[end:]
            position = match.start()
    return entry


def resolve_corpus(bibs: list[Path]) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Merge every direction bib into one key map, reporting cross-direction clashes.

    A key defined in two directions is a one-master-rule violation in the corpus
    itself: whichever copy a generator happens to pick, the other silently stops
    being the citation. It is reported rather than resolved, because picking a
    winner is a curation decision and not this script's to make.
    """
    available: dict[str, str] = {}
    seen_in: dict[str, list[str]] = {}
    for path in bibs:
        direction = path.parent.name
        text = path.read_text(encoding="utf-8")
        parsed = parse_entries(text)
        # entry_keys, not parsed.items(): the repeats have to survive to here,
        # or a within-file duplicate is resolved silently one level down.
        for key in entry_keys(text):
            available.setdefault(key, parsed[key])
            seen_in.setdefault(key, []).append(direction)
    duplicated = {key: names for key, names in seen_in.items() if len(names) > 1}
    return available, duplicated


def render(available: dict[str, str], keys: set[str], sources: list[Path]) -> str:
    """The exact bytes a kit's ``paper.bib`` should contain.

    Split out of ``build`` so that "is this kit stale?" can be answered by
    calling the renderer rather than by re-deriving what it does. A staleness
    check that reimplements the generator only tests the generator it was
    written against: this one asserted the verbatim master entry appeared on
    disk, and went red the first time the generator legitimately transformed an
    entry (curation-field stripping, 2026-08-21).
    """
    header = (
        f"{GENERATED_MARKER} -- do not edit.\n"
        "% The cited subset of science's literature/*/references.bib, keys unchanged.\n"
        f"% Sources: {', '.join(path.parent.name for path in sources)}\n"
    )
    # Curation metadata stops here: the master keeps its note, the venue bib
    # never carries one. See CURATION_FIELDS.
    body = "\n\n".join(strip_curation_fields(available[key]) for key in sorted(keys))
    return header + "\n" + body + "\n"


def build(paper_id: str, *, corpus: Path) -> tuple[int, list[Path]]:
    """Write every kit's ``paper.bib`` for *paper_id*. Returns (n_keys, kits)."""
    paper_dir = PAPER_ROOT / paper_id
    if not paper_dir.is_dir():
        raise SystemExit(f"no such paper directory: {paper_dir}")

    bibs = master_bibs(corpus)
    if not bibs:
        raise SystemExit(
            f"no direction bibs under {corpus}\n"
            "set SCIENCE_LITERATURE_DIR to the science organ's literature/ directory"
        )

    available, duplicated = resolve_corpus(bibs)
    if duplicated:
        lines = []
        for key, names in sorted(duplicated.items()):
            if len(set(names)) == 1:
                lines.append(f"{key}: {len(names)}x within {names[0]}")
            else:
                lines.append(f"{key}: across {', '.join(sorted(set(names)))}")
        raise SystemExit(
            "one key, one entry -- the corpus defines a key more than once, so\n"
            "merge or rename it there before generating:\n  " + "\n  ".join(lines)
        )

    tex_files = sorted(paper_dir.rglob("paper.tex"))
    if not tex_files:
        raise SystemExit(f"no paper.tex under {paper_dir}")

    keys: set[str] = set()
    for tex in tex_files:
        keys |= cited_keys(tex.read_text(encoding="utf-8"))

    missing = sorted(key for key in keys if key not in available)
    if missing:
        raise SystemExit(
            "cited keys absent from the shared corpus -- add them to the right\n"
            "direction's references.bib FIRST (one-master rule), never here:\n  "
            + "\n  ".join(missing)
        )

    text = render(available, keys, bibs)

    written = []
    for tex in tex_files:
        out = tex.with_name("paper.bib")
        out.write_text(text, encoding="utf-8")
        written.append(out)
    return len(keys), written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paper_id", help="a directory name under paper/, e.g. as-6")
    parser.add_argument(
        "--corpus",
        type=Path,
        default=None,
        help="override the shared-corpus directory (else $SCIENCE_LITERATURE_DIR)",
    )
    args = parser.parse_args(argv)

    resolved = args.corpus.expanduser().resolve() if args.corpus else corpus_dir()
    count, written = build(args.paper_id, corpus=resolved)
    print(f"corpus: {resolved}")
    print(f"resolved {count} cited keys")
    for path in written:
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
