"""Generate a paper kit's ``paper.bib`` as the CITED SUBSET of the shared corpus.

The one-master rule (``paper/literature/README.md``): the shared bib lives in the
science organ, one master per DIRECTION, and a paper repo's own bib is a subset
copied out of it with **keys unchanged**. A second hand-written bib is the
dual-truth failure with citation keys -- a key that drifts between two bibs
produces a wrong citation that compiles cleanly. So this file exists to make the
venue bib build output rather than a source of truth.

Two properties are deliberate:

* **It fails loudly on an unresolved key.** A cited key with no entry renders as
  a bare ``?`` in the PDF, which is the failure mode a silent generator would
  ship. Missing keys are an error, never a warning.
* **It reads EVERY direction bib, not one.** The corpus has one master per
  direction and a paper cites across them; measuring a key's absence against a
  single index and reporting it as absence in general is a recorded defect in
  this repo (``CLAUDE.md``, and ``as6/evidence_and_story.md`` §5.2 where it
  nearly duplicated four entries).

The corpus location is NOT hard-coded: this repo is public, so an absolute path
would commit the owner's directory layout. It resolves from
``$SCIENCE_LITERATURE_DIR`` if set, else from a path relative to this checkout.

Keyless, no network, no model. Run it, then rebuild the kit::

    uv run python scripts/build_venue_bib.py as-6
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PAPER_ROOT = REPO_ROOT / "paper"

#: Where the shared corpus sits relative to this checkout, when the env var is
#: unset. Deliberately relative -- see the module docstring.
DEFAULT_CORPUS_RELATIVE = Path("..") / ".." / "personal" / "science" / "literature"

#: Every ``\cite``-family command natbib gives us. The trailing ``\*?`` catches
#: the starred forms, and the optional-argument groups catch ``\citep[see][]{k}``.
CITE_PATTERN = re.compile(
    r"\\(?:no)?cite[a-zA-Z]*\*?\s*(?:\[[^\]]*\]\s*){0,2}\{([^}]*)\}"
)

#: A whole-line LaTeX comment. Keys inside commented-out prose are not cited.
COMMENT_PATTERN = re.compile(r"(?m)^\s*%.*$")

#: The start of a BibTeX entry, capturing its key.
ENTRY_PATTERN = re.compile(r"(?m)^@(\w+)\s*\{\s*([^,\s]+)\s*,")

#: First line of a generated bib. It is the marker that says "this kit is on the
#: one-master rule", and tests scope themselves to kits carrying it -- so a kit
#: still on a hand-written bib is visibly OUT of coverage rather than silently
#: passing, and joins coverage the moment it is migrated.
GENERATED_MARKER = "% GENERATED by scripts/build_venue_bib.py"


def corpus_dir() -> Path:
    """Resolve the shared-corpus directory, env var winning over the default."""
    override = os.environ.get("SCIENCE_LITERATURE_DIR")
    if override:
        return Path(override).expanduser().resolve()
    return (REPO_ROOT / DEFAULT_CORPUS_RELATIVE).resolve()


def master_bibs(corpus: Path) -> list[Path]:
    """Every direction's ``references.bib``, sorted for a deterministic output."""
    return sorted(corpus.glob("*/references.bib"))


def cited_keys(tex: str) -> set[str]:
    """Extract every key cited by *tex*, ignoring whole-line comments."""
    body = COMMENT_PATTERN.sub("", tex)
    keys: set[str] = set()
    for group in CITE_PATTERN.findall(body):
        # A `%` line-continuation inside a \citep{a,b%\n c} list survives the
        # comment strip above, because it is not a whole-line comment.
        for key in group.replace("%", " ").split(","):
            key = key.strip()
            if key:
                keys.add(key)
    return keys


def parse_entries(bib: str) -> dict[str, str]:
    """Split a bib file into ``{key: entry text}`` by brace matching.

    Brace matching rather than a regex on ``\n}``: entries here carry ``note``
    fields with braces inside them, and a line-anchored terminator truncates
    those silently.
    """
    entries: dict[str, str] = {}
    for match in ENTRY_PATTERN.finditer(bib):
        start = match.start()
        depth = 0
        index = bib.index("{", start)
        for position in range(index, len(bib)):
            character = bib[position]
            if character == "{":
                depth += 1
            elif character == "}":
                depth -= 1
                if depth == 0:
                    entries[match.group(2)] = bib[start : position + 1]
                    break
    return entries


def resolve_corpus(bibs: list[Path]) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Merge every direction bib into one key map, reporting cross-direction clashes.

    A key defined in two directions is a one-master-rule violation in the corpus
    itself: whichever copy a generator happens to pick, the other silently stops
    being the citation. It is reported rather than resolved, because picking a
    winner is a curation decision and not this script's to make.
    """
    available: dict[str, str] = {}
    seen_in: dict[str, list[str]] = {}
    for path in bibs:
        direction = path.parent.name
        for key, entry in parse_entries(path.read_text(encoding="utf-8")).items():
            available.setdefault(key, entry)
            seen_in.setdefault(key, []).append(direction)
    duplicated = {key: names for key, names in seen_in.items() if len(names) > 1}
    return available, duplicated


def build(paper_id: str, *, corpus: Path) -> tuple[int, list[Path]]:
    """Write every kit's ``paper.bib`` for *paper_id*. Returns (n_keys, kits)."""
    paper_dir = PAPER_ROOT / paper_id
    if not paper_dir.is_dir():
        raise SystemExit(f"no such paper directory: {paper_dir}")

    bibs = master_bibs(corpus)
    if not bibs:
        raise SystemExit(
            f"no direction bibs under {corpus}\n"
            "set SCIENCE_LITERATURE_DIR to the science organ's literature/ directory"
        )

    available, duplicated = resolve_corpus(bibs)
    if duplicated:
        raise SystemExit(
            "the same key is defined in more than one direction bib -- one master\n"
            "per key, so merge or rename in the corpus before generating:\n  "
            + "\n  ".join(
                f"{key}: {', '.join(names)}" for key, names in sorted(duplicated.items())
            )
        )

    tex_files = sorted(paper_dir.rglob("paper.tex"))
    if not tex_files:
        raise SystemExit(f"no paper.tex under {paper_dir}")

    keys: set[str] = set()
    for tex in tex_files:
        keys |= cited_keys(tex.read_text(encoding="utf-8"))

    missing = sorted(key for key in keys if key not in available)
    if missing:
        raise SystemExit(
            "cited keys absent from the shared corpus -- add them to the right\n"
            "direction's references.bib FIRST (one-master rule), never here:\n  "
            + "\n  ".join(missing)
        )

    header = (
        f"{GENERATED_MARKER} -- do not edit.\n"
        "% The cited subset of science's literature/*/references.bib, keys unchanged.\n"
        f"% Sources: {', '.join(path.parent.name for path in bibs)}\n"
    )
    body = "\n\n".join(available[key] for key in sorted(keys))

    written = []
    for tex in tex_files:
        out = tex.with_name("paper.bib")
        out.write_text(header + "\n" + body + "\n", encoding="utf-8")
        written.append(out)
    return len(keys), written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paper_id", help="a directory name under paper/, e.g. as-6")
    parser.add_argument(
        "--corpus",
        type=Path,
        default=None,
        help="override the shared-corpus directory (else $SCIENCE_LITERATURE_DIR)",
    )
    args = parser.parse_args(argv)

    resolved = args.corpus.expanduser().resolve() if args.corpus else corpus_dir()
    count, written = build(args.paper_id, corpus=resolved)
    print(f"corpus: {resolved}")
    print(f"resolved {count} cited keys")
    for path in written:
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
